/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-auto-import-components
export {}
declare global {
  // 组件类型
  const MyButton: typeof import('@/components/MyButton')['default']
  const MyInput: typeof import('@/components/MyInput')['default']
  const MyInput1: typeof import('@/components/MyInput1')['default']

  // React Hooks类型
  const useState: typeof import('react')['useState']
  const useEffect: typeof import('react')['useEffect']
  const useContext: typeof import('react')['useContext']
  const useReducer: typeof import('react')['useReducer']
  const useCallback: typeof import('react')['useCallback']
  const useMemo: typeof import('react')['useMemo']
  const useRef: typeof import('react')['useRef']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useLayoutEffect: typeof import('react')['useLayoutEffect']
  const useDebugValue: typeof import('react')['useDebugValue']
}
